name: flutter_hypertension_monitor 
description: An app to register and monitor hypertension related values 
version: 1.0.0

environment:
  sdk: ">=3.12.0 <4.0.0"

dependencies: 
  flutter: 
    sdk: flutter

  cupertino_icons: ^1.0.8

  # state management 
  flutter_riverpod: ^3.0.0
  
  # navigation 
  #go_router: ^16.0.0  # da togliere 

  # local database
  # si utilizza hive community edition perché è attivamente mantenuta
  hive_ce: ^2.15.0
  hive_ce_flutter: ^2.3.4
  # path_provider è già una dipendenza di hive_ce_flutter

  # utilities 
  shared_preferences: ^2.5.5
  fl_chart: ^1.1.1
  intl: ^0.20.2
  uuid: ^4.5.1


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  build_runner: ^2.5.4
  hive_ce_generator: ^1.9.2
