// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive_ce.dart';
import 'package:flutter_hypertension_monitor/core/user/user_role.dart';
import 'package:flutter_hypertension_monitor/data/models/blood_pressure_measurement.dart';
import 'package:flutter_hypertension_monitor/data/models/medical_history.dart';
import 'package:flutter_hypertension_monitor/data/models/patient.dart';
import 'package:flutter_hypertension_monitor/data/models/user.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(BloodPressureMeasurementAdapter());
    registerAdapter(MedicalHistoryAdapter());
    registerAdapter(PatientAdapter());
    registerAdapter(UserAdapter());
    registerAdapter(UserRoleAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(BloodPressureMeasurementAdapter());
    registerAdapter(MedicalHistoryAdapter());
    registerAdapter(PatientAdapter());
    registerAdapter(UserAdapter());
    registerAdapter(UserRoleAdapter());
  }
}
